<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Npgsql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DecisionForge.Application\DecisionForge.Application.csproj" />
    <ProjectReference Include="..\DecisionForge.Infrastructure\DecisionForge.Infrastructure.csproj" />
    <ProjectReference Include="..\DecisionForge.ServiceDefaults\DecisionForge.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
